version: "3"

services:
  db:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=sachinholla2001
      - MYSQL_DATABASE=db_fintech
    networks:
      - myNet
    volumes:
      - ./for-mysql/db_fintech_dump.sql:/docker-entrypoint-initdb.d/db_fintech_dump.sql
   

  frontend:
    build:
      context: ./frontend/
    image: banking-frontend
    ports:
      - 3000:3000
    networks:
      - myNet
    depends_on:
      - backend

  backend:
    build: ./backend
    image: banking-backend
    ports:
      - 3003:3003
    volumes:
      - myvolumes:/backend
    networks:
      - myNet
    depends_on:
      - db

volumes:
  myvolumes:

networks:
  myNet:
    driver: bridge
